//next components
import Head from 'next/head'

//components
import Game from '../components/Game'

export default function Home() {
  return (
    <>
      <Head>
        <title>Tic Tac Toe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="favicon.jpg" type="image/x-icon" />
      </Head>

      <Game />
    </>
  )
}
